name: che155
channels:
    - conda-forge
    - psi4
    - rdkit
    - defaults
dependencies:
    - numpy>=1.19
    - scipy>=1.6
    - python=3.7    
    - matplotlib
    - jupyterlab=2
    - ipyparallel
    - ipympl
    - ipywidgets
    - plotly
    - pandas>=1.2
    - pingouin>=0.3.10
    - tabulate
    - scikit-image
    - psi4
    - psi4-rt
    - openmm
    - rdkit
    - openbabel
    - mdtraj
    - geometric
    - networkx
    - nglview
    - nodejs
    - pip
    - pip:
      - tables==3.6.1
    
